[package]
name = "vda5050-import"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
hex.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["arbitrary_precision"] }
sha2.workspace = true
thiserror.workspace = true
vda5050-core = { version = "0.2.0", path = "../vda5050-core" }
vda5050-local-fs.workspace = true

[dev-dependencies]
tempfile = "3.23"

[lints]
workspace = true
