listener 1883
protocol mqtt
listener_allow_anonymous true

persistence false
allow_zero_length_clientid false
connection_messages true
retain_available true
max_qos 1
max_connections 104
max_inflight_messages 32
max_queued_messages 64
max_packet_size 1048576

log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
